services:
  element:
    image: odva/phalcon:5.0
    networks:
      - element
    container_name: ${CONTAINER_NAME-element}
    restart: 'no'
    ports:
      - "${PORT-85}:80"
    volumes:
      - ${ELEMENT_DIR-./}:/var/www/element
    working_dir: ${WORKDIR-/var/www/element}
networks:
  element:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.100.${SITE_ID-1}.0/24