services:
  application:
    container_name: 'element-develop'
    image: odva/lamp:8.4
    ports:
      - 8081:80
    volumes:
      - ./:/var/www
      - ./dev-logs:/var/log/apache2
    networks:
      - mariadb_default
networks:
  mariadb_default:
    driver: default
    external: true